name = "GraftImpurity"
uuid = "05920a16-b046-4d42-a2c4-f5ac0fa0c24c"
version = "0.1.1"
authors = ["weiyiguo9"]
license = "Apache-2.0"

[deps]
GraftImpurityBathFit = "e3ae8f75-a118-47e7-8672-9ebafe45b6d5"
GraftImpurityBaths = "5c03999c-56bc-4780-9d5e-8bfeabf3ad62"
GraftImpurityFoundations = "3c703997-107e-47af-a3a4-2068413d67cf"
GraftImpurityInteractions = "ff38f452-5450-47a1-bb7b-3484d76418db"
GraftImpurityPoleFits = "bc763d54-c6dc-4f25-bb71-83535c88eea5"
GraftImpurityProblems = "72127451-eddd-47b0-aca9-ed50881d020e"
GraftTTNSSolver = "671ba014-2ccc-4013-b4e5-eebb41b7846b"
GraftImpurityValidation = "c9b6821c-9786-4062-96a1-3ad33b52b59d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[sources]
GraftImpurityBathFit = {path = "lib/GraftImpurityBathFit"}
GraftImpurityBaths = {path = "lib/GraftImpurityBaths"}
GraftImpurityFoundations = {path = "lib/GraftImpurityFoundations"}
GraftImpurityInteractions = {path = "lib/GraftImpurityInteractions"}
GraftImpurityPoleFits = {path = "lib/GraftImpurityPoleFits"}
GraftImpurityProblems = {path = "lib/GraftImpurityProblems"}
GraftTTNSSolver = {path = "lib/GraftTTNSSolver"}
GraftImpurityValidation = {path = "lib/GraftImpurityValidation"}

[compat]
GraftImpurityBathFit = "0.1.1"
GraftImpurityBaths = "0.1.1"
GraftImpurityFoundations = "0.1.1"
GraftImpurityInteractions = "0.1.1"
GraftImpurityPoleFits = "0.1.1"
GraftImpurityProblems = "0.1.1"
GraftTTNSSolver = "0.1.1"
GraftImpurityValidation = "0.1.1"
PrecompileTools = "1.3.4"
julia = "1.11"
